services:
  typebot-builder:
    depends_on:
      typebot-db:
        condition: service_healthy
    env_file: .env
    extra_hosts:
      - host.docker.internal:host-gateway
    image: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1563457855438522/baptistearno/typebot-builder:latest
    ports:
      - 8080:3000
    restart: always
  typebot-db:
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
    healthcheck:
      interval: 5s
      retries: 5
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      timeout: 5s
    image: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1563457855438522/postgres:16
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
  typebot-viewer:
    depends_on:
      typebot-db:
        condition: service_healthy
    env_file: .env
    image: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1563457855438522/baptistearno/typebot-viewer:latest
    ports:
      - 8081:3000
    restart: always
version: '3.3'
volumes:
  db-data: null